# Generated by Django 3.2.18 on 2025-04-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('shipment_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('ripeness_status', models.CharField(choices=[('unripe', 'Unripe'), ('freshripe', 'Fresh Ripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('dominant_ripeness', models.CharField(choices=[('unripe', 'Unripe'), ('freshripe', 'Fresh Ripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('ripeness_summary', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('predictions', djongo.models.fields.JSONField(blank=True, default=list)),
                ('shelf_life', models.IntegerField(default=0)),
                ('alert_sent', models.BooleanField(default=False)),
                ('result_image', models.TextField(blank=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('optimized_route', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BananaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shipments.shipment')),
            ],
        ),
    ]
