# Generated by Django 3.2.18 on 2025-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
